- name: Deploying Infrastructure
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:

  - name: Fail when environment is not aws
    fail:
      msg: "Current target environment is {{ input.environment }}"
    when: input.environment.aws is undefined


