- name: Deploying Infrastructure
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:

  - name: Fail when environment is not azure
    fail:
    when: input.environment.azure is undefined

