- name: Deploying Infrastructure
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:

    - name: Fail when environment is not azure
    fail:
      msg: "Current target environment is {{ input.environment }}"
    when: input.environment.azure is undefined

